# Generated by Django 5.2.8 on 2025-11-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('Notes', 'Notes'), ('Lab Programs', 'Lab Programs'), ('Question Papers', 'Question Papers'), ('Mini Projects', 'Mini Projects'), ('other', 'Other')], max_length=20),
        ),
    ]
